/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedActivitesRouteImport } from './routes/_authed/activites'
import { Route as AuthedBienvenueRouteImport } from './routes/_authed/bienvenue'
import { Route as AuthedDemandesRouteImport } from './routes/_authed/demandes'
import { Route as AuthedEnfantsRouteImport } from './routes/_authed/enfants'
import { Route as AuthedEquilibreRouteImport } from './routes/_authed/equilibre'
import { Route as AuthedFoyerRouteImport } from './routes/_authed/foyer'
import { Route as AuthedHubsRouteImport } from './routes/_authed/hubs'
import { Route as AuthedSemaineRouteImport } from './routes/_authed/semaine'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedActivitesRoute = AuthedActivitesRouteImport.update({
  id: '/activites',
  path: '/activites',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBienvenueRoute = AuthedBienvenueRouteImport.update({
  id: '/bienvenue',
  path: '/bienvenue',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDemandesRoute = AuthedDemandesRouteImport.update({
  id: '/demandes',
  path: '/demandes',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEnfantsRoute = AuthedEnfantsRouteImport.update({
  id: '/enfants',
  path: '/enfants',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEquilibreRoute = AuthedEquilibreRouteImport.update({
  id: '/equilibre',
  path: '/equilibre',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFoyerRoute = AuthedFoyerRouteImport.update({
  id: '/foyer',
  path: '/foyer',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHubsRoute = AuthedHubsRouteImport.update({
  id: '/hubs',
  path: '/hubs',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSemaineRoute = AuthedSemaineRouteImport.update({
  id: '/semaine',
  path: '/semaine',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activites': typeof AuthedActivitesRoute
  '/bienvenue': typeof AuthedBienvenueRoute
  '/demandes': typeof AuthedDemandesRoute
  '/enfants': typeof AuthedEnfantsRoute
  '/equilibre': typeof AuthedEquilibreRoute
  '/foyer': typeof AuthedFoyerRoute
  '/hubs': typeof AuthedHubsRoute
  '/semaine': typeof AuthedSemaineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activites': typeof AuthedActivitesRoute
  '/bienvenue': typeof AuthedBienvenueRoute
  '/demandes': typeof AuthedDemandesRoute
  '/enfants': typeof AuthedEnfantsRoute
  '/equilibre': typeof AuthedEquilibreRoute
  '/foyer': typeof AuthedFoyerRoute
  '/hubs': typeof AuthedHubsRoute
  '/semaine': typeof AuthedSemaineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/activites': typeof AuthedActivitesRoute
  '/_authed/bienvenue': typeof AuthedBienvenueRoute
  '/_authed/demandes': typeof AuthedDemandesRoute
  '/_authed/enfants': typeof AuthedEnfantsRoute
  '/_authed/equilibre': typeof AuthedEquilibreRoute
  '/_authed/foyer': typeof AuthedFoyerRoute
  '/_authed/hubs': typeof AuthedHubsRoute
  '/_authed/semaine': typeof AuthedSemaineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/activites'
    | '/bienvenue'
    | '/demandes'
    | '/enfants'
    | '/equilibre'
    | '/foyer'
    | '/hubs'
    | '/semaine'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/activites'
    | '/bienvenue'
    | '/demandes'
    | '/enfants'
    | '/equilibre'
    | '/foyer'
    | '/hubs'
    | '/semaine'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/activites'
    | '/_authed/bienvenue'
    | '/_authed/demandes'
    | '/_authed/enfants'
    | '/_authed/equilibre'
    | '/_authed/foyer'
    | '/_authed/hubs'
    | '/_authed/semaine'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/activites': {
      id: '/_authed/activites'
      path: '/activites'
      fullPath: '/activites'
      preLoaderRoute: typeof AuthedActivitesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/bienvenue': {
      id: '/_authed/bienvenue'
      path: '/bienvenue'
      fullPath: '/bienvenue'
      preLoaderRoute: typeof AuthedBienvenueRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/demandes': {
      id: '/_authed/demandes'
      path: '/demandes'
      fullPath: '/demandes'
      preLoaderRoute: typeof AuthedDemandesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/enfants': {
      id: '/_authed/enfants'
      path: '/enfants'
      fullPath: '/enfants'
      preLoaderRoute: typeof AuthedEnfantsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/equilibre': {
      id: '/_authed/equilibre'
      path: '/equilibre'
      fullPath: '/equilibre'
      preLoaderRoute: typeof AuthedEquilibreRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/foyer': {
      id: '/_authed/foyer'
      path: '/foyer'
      fullPath: '/foyer'
      preLoaderRoute: typeof AuthedFoyerRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/hubs': {
      id: '/_authed/hubs'
      path: '/hubs'
      fullPath: '/hubs'
      preLoaderRoute: typeof AuthedHubsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/semaine': {
      id: '/_authed/semaine'
      path: '/semaine'
      fullPath: '/semaine'
      preLoaderRoute: typeof AuthedSemaineRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedActivitesRoute: typeof AuthedActivitesRoute
  AuthedBienvenueRoute: typeof AuthedBienvenueRoute
  AuthedDemandesRoute: typeof AuthedDemandesRoute
  AuthedEnfantsRoute: typeof AuthedEnfantsRoute
  AuthedEquilibreRoute: typeof AuthedEquilibreRoute
  AuthedFoyerRoute: typeof AuthedFoyerRoute
  AuthedHubsRoute: typeof AuthedHubsRoute
  AuthedSemaineRoute: typeof AuthedSemaineRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedActivitesRoute: AuthedActivitesRoute,
  AuthedBienvenueRoute: AuthedBienvenueRoute,
  AuthedDemandesRoute: AuthedDemandesRoute,
  AuthedEnfantsRoute: AuthedEnfantsRoute,
  AuthedEquilibreRoute: AuthedEquilibreRoute,
  AuthedFoyerRoute: AuthedFoyerRoute,
  AuthedHubsRoute: AuthedHubsRoute,
  AuthedSemaineRoute: AuthedSemaineRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
